// flow-typed signature: 64e7962efd6fe38fb854a215a626030e
// flow-typed version: <<STUB>>/@zip.js/zip.js_v^2.8.26/flow_v0.314.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zip.js/zip.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zip.js/zip.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@zip.js/zip.js/dist/zip-core' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-core.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs-core' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs-core.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs-native.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-fs.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-legacy' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-legacy.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-native.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-web-worker-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip-web-worker' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/dist/zip.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/index-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/index-native.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/index.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/codec-pool' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/codec-worker' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/configuration' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/constants' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/io' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/options' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/aes-crypto-stream' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/codec-stream' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/codecs/crc32' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/codecs/sjcl' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/common-crypto' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/crc32-stream' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/zip-crypto-stream' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/zip-entry-stream' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/zlib-js/zlib-streams.min' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams-loader' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/decode-cp437' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/decode-text' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/default-mime-type' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/encode-text' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/mime-type' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/util/mini-lz' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-base' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-inline-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-inline-template-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-inline-template' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-inline-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/web-worker-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zip-entry' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zip-fs' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zip-reader' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zip-writer' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zlib-streams-inline-template' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/core/zlib-streams-inline' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core-base' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core-reader' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core-writer' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-core' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-fs-core-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-fs-core-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-fs-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-fs-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-legacy' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-module-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-module-wasm' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-native' {
  declare module.exports: any;
}

declare module '@zip.js/zip.js/lib/zip-wasm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@zip.js/zip.js/dist/zip-core.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-core'>;
}
declare module '@zip.js/zip.js/dist/zip-core.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-core.min'>;
}
declare module '@zip.js/zip.js/dist/zip-fs-core.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs-core'>;
}
declare module '@zip.js/zip.js/dist/zip-fs-core.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs-core.min'>;
}
declare module '@zip.js/zip.js/dist/zip-fs-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs-native'>;
}
declare module '@zip.js/zip.js/dist/zip-fs-native.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs-native.min'>;
}
declare module '@zip.js/zip.js/dist/zip-fs.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs'>;
}
declare module '@zip.js/zip.js/dist/zip-fs.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-fs.min'>;
}
declare module '@zip.js/zip.js/dist/zip-legacy.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-legacy'>;
}
declare module '@zip.js/zip.js/dist/zip-legacy.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-legacy.min'>;
}
declare module '@zip.js/zip.js/dist/zip-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-native'>;
}
declare module '@zip.js/zip.js/dist/zip-native.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-native.min'>;
}
declare module '@zip.js/zip.js/dist/zip-web-worker-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-web-worker-native'>;
}
declare module '@zip.js/zip.js/dist/zip-web-worker.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip-web-worker'>;
}
declare module '@zip.js/zip.js/dist/zip.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip'>;
}
declare module '@zip.js/zip.js/dist/zip.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/dist/zip.min'>;
}
declare module '@zip.js/zip.js/index-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/index-native'>;
}
declare module '@zip.js/zip.js/index-native.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/index-native.min'>;
}
declare module '@zip.js/zip.js/index' {
  declare module.exports: $Exports<'@zip.js/zip.js'>;
}
declare module '@zip.js/zip.js/index.js' {
  declare module.exports: $Exports<'@zip.js/zip.js'>;
}
declare module '@zip.js/zip.js/index.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/index.min'>;
}
declare module '@zip.js/zip.js/lib/core/codec-pool.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/codec-pool'>;
}
declare module '@zip.js/zip.js/lib/core/codec-worker.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/codec-worker'>;
}
declare module '@zip.js/zip.js/lib/core/configuration.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/configuration'>;
}
declare module '@zip.js/zip.js/lib/core/constants.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/constants'>;
}
declare module '@zip.js/zip.js/lib/core/io.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/io'>;
}
declare module '@zip.js/zip.js/lib/core/options.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/options'>;
}
declare module '@zip.js/zip.js/lib/core/streams/aes-crypto-stream.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/aes-crypto-stream'>;
}
declare module '@zip.js/zip.js/lib/core/streams/codec-stream.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/codec-stream'>;
}
declare module '@zip.js/zip.js/lib/core/streams/codecs/crc32.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/codecs/crc32'>;
}
declare module '@zip.js/zip.js/lib/core/streams/codecs/sjcl.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/codecs/sjcl'>;
}
declare module '@zip.js/zip.js/lib/core/streams/common-crypto.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/common-crypto'>;
}
declare module '@zip.js/zip.js/lib/core/streams/crc32-stream.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/crc32-stream'>;
}
declare module '@zip.js/zip.js/lib/core/streams/zip-crypto-stream.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/zip-crypto-stream'>;
}
declare module '@zip.js/zip.js/lib/core/streams/zip-entry-stream.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/zip-entry-stream'>;
}
declare module '@zip.js/zip.js/lib/core/streams/zlib-js/zlib-streams.min.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/zlib-js/zlib-streams.min'>;
}
declare module '@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams-loader.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams-loader'>;
}
declare module '@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/streams/zlib-wasm/zlib-streams'>;
}
declare module '@zip.js/zip.js/lib/core/util/decode-cp437.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/decode-cp437'>;
}
declare module '@zip.js/zip.js/lib/core/util/decode-text.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/decode-text'>;
}
declare module '@zip.js/zip.js/lib/core/util/default-mime-type.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/default-mime-type'>;
}
declare module '@zip.js/zip.js/lib/core/util/encode-text.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/encode-text'>;
}
declare module '@zip.js/zip.js/lib/core/util/mime-type.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/mime-type'>;
}
declare module '@zip.js/zip.js/lib/core/util/mini-lz.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/util/mini-lz'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-base.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-base'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-inline-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-inline-native'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-inline-template-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-inline-template-native'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-inline-template.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-inline-template'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-inline-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-inline-wasm'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-native'>;
}
declare module '@zip.js/zip.js/lib/core/web-worker-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/web-worker-wasm'>;
}
declare module '@zip.js/zip.js/lib/core/zip-entry.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zip-entry'>;
}
declare module '@zip.js/zip.js/lib/core/zip-fs.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zip-fs'>;
}
declare module '@zip.js/zip.js/lib/core/zip-reader.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zip-reader'>;
}
declare module '@zip.js/zip.js/lib/core/zip-writer.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zip-writer'>;
}
declare module '@zip.js/zip.js/lib/core/zlib-streams-inline-template.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zlib-streams-inline-template'>;
}
declare module '@zip.js/zip.js/lib/core/zlib-streams-inline.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/core/zlib-streams-inline'>;
}
declare module '@zip.js/zip.js/lib/zip-core-base.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core-base'>;
}
declare module '@zip.js/zip.js/lib/zip-core-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core-native'>;
}
declare module '@zip.js/zip.js/lib/zip-core-reader.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core-reader'>;
}
declare module '@zip.js/zip.js/lib/zip-core-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core-wasm'>;
}
declare module '@zip.js/zip.js/lib/zip-core-writer.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core-writer'>;
}
declare module '@zip.js/zip.js/lib/zip-core.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-core'>;
}
declare module '@zip.js/zip.js/lib/zip-fs-core-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-fs-core-native'>;
}
declare module '@zip.js/zip.js/lib/zip-fs-core-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-fs-core-wasm'>;
}
declare module '@zip.js/zip.js/lib/zip-fs-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-fs-native'>;
}
declare module '@zip.js/zip.js/lib/zip-fs-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-fs-wasm'>;
}
declare module '@zip.js/zip.js/lib/zip-legacy.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-legacy'>;
}
declare module '@zip.js/zip.js/lib/zip-module-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-module-native'>;
}
declare module '@zip.js/zip.js/lib/zip-module-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-module-wasm'>;
}
declare module '@zip.js/zip.js/lib/zip-native.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-native'>;
}
declare module '@zip.js/zip.js/lib/zip-wasm.js' {
  declare module.exports: $Exports<'@zip.js/zip.js/lib/zip-wasm'>;
}
