// flow-typed signature: cdd5d309721472ad177aedcd4a49e623
// flow-typed version: <<STUB>>/async-mutex_v^0.5/flow_v0.314.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-mutex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-mutex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-mutex/es6/errors' {
  declare module.exports: any;
}

declare module 'async-mutex/es6' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/Mutex' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/MutexInterface' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/Semaphore' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/SemaphoreInterface' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/tryAcquire' {
  declare module.exports: any;
}

declare module 'async-mutex/es6/withTimeout' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/errors' {
  declare module.exports: any;
}

declare module 'async-mutex/lib' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/Mutex' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/MutexInterface' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/Semaphore' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/SemaphoreInterface' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/tryAcquire' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/withTimeout' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-mutex/es6/errors.js' {
  declare module.exports: $Exports<'async-mutex/es6/errors'>;
}
declare module 'async-mutex/es6/index' {
  declare module.exports: $Exports<'async-mutex/es6'>;
}
declare module 'async-mutex/es6/index.js' {
  declare module.exports: $Exports<'async-mutex/es6'>;
}
declare module 'async-mutex/es6/Mutex.js' {
  declare module.exports: $Exports<'async-mutex/es6/Mutex'>;
}
declare module 'async-mutex/es6/MutexInterface.js' {
  declare module.exports: $Exports<'async-mutex/es6/MutexInterface'>;
}
declare module 'async-mutex/es6/Semaphore.js' {
  declare module.exports: $Exports<'async-mutex/es6/Semaphore'>;
}
declare module 'async-mutex/es6/SemaphoreInterface.js' {
  declare module.exports: $Exports<'async-mutex/es6/SemaphoreInterface'>;
}
declare module 'async-mutex/es6/tryAcquire.js' {
  declare module.exports: $Exports<'async-mutex/es6/tryAcquire'>;
}
declare module 'async-mutex/es6/withTimeout.js' {
  declare module.exports: $Exports<'async-mutex/es6/withTimeout'>;
}
declare module 'async-mutex/lib/errors.js' {
  declare module.exports: $Exports<'async-mutex/lib/errors'>;
}
declare module 'async-mutex/lib/index' {
  declare module.exports: $Exports<'async-mutex/lib'>;
}
declare module 'async-mutex/lib/index.js' {
  declare module.exports: $Exports<'async-mutex/lib'>;
}
declare module 'async-mutex/lib/Mutex.js' {
  declare module.exports: $Exports<'async-mutex/lib/Mutex'>;
}
declare module 'async-mutex/lib/MutexInterface.js' {
  declare module.exports: $Exports<'async-mutex/lib/MutexInterface'>;
}
declare module 'async-mutex/lib/Semaphore.js' {
  declare module.exports: $Exports<'async-mutex/lib/Semaphore'>;
}
declare module 'async-mutex/lib/SemaphoreInterface.js' {
  declare module.exports: $Exports<'async-mutex/lib/SemaphoreInterface'>;
}
declare module 'async-mutex/lib/tryAcquire.js' {
  declare module.exports: $Exports<'async-mutex/lib/tryAcquire'>;
}
declare module 'async-mutex/lib/withTimeout.js' {
  declare module.exports: $Exports<'async-mutex/lib/withTimeout'>;
}
