// flow-typed signature: b35a4f3f479696ca6313f8b5c368a4c9
// flow-typed version: <<STUB>>/i18next-http-backend_v^4.0.0/flow_v0.294.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-http-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-http-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-http-backend/cjs' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/esm' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/i18nextHttpBackend' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/i18nextHttpBackend.min' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/lib' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/lib/request' {
  declare module.exports: any;
}

declare module 'i18next-http-backend/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-http-backend/cjs/index' {
  declare module.exports: $Exports<'i18next-http-backend/cjs'>;
}
declare module 'i18next-http-backend/cjs/index.js' {
  declare module.exports: $Exports<'i18next-http-backend/cjs'>;
}
declare module 'i18next-http-backend/esm/index' {
  declare module.exports: $Exports<'i18next-http-backend/esm'>;
}
declare module 'i18next-http-backend/esm/index.js' {
  declare module.exports: $Exports<'i18next-http-backend/esm'>;
}
declare module 'i18next-http-backend/i18nextHttpBackend.js' {
  declare module.exports: $Exports<'i18next-http-backend/i18nextHttpBackend'>;
}
declare module 'i18next-http-backend/i18nextHttpBackend.min.js' {
  declare module.exports: $Exports<'i18next-http-backend/i18nextHttpBackend.min'>;
}
declare module 'i18next-http-backend/index' {
  declare module.exports: $Exports<'i18next-http-backend'>;
}
declare module 'i18next-http-backend/index.js' {
  declare module.exports: $Exports<'i18next-http-backend'>;
}
declare module 'i18next-http-backend/lib/index' {
  declare module.exports: $Exports<'i18next-http-backend/lib'>;
}
declare module 'i18next-http-backend/lib/index.js' {
  declare module.exports: $Exports<'i18next-http-backend/lib'>;
}
declare module 'i18next-http-backend/lib/request.js' {
  declare module.exports: $Exports<'i18next-http-backend/lib/request'>;
}
declare module 'i18next-http-backend/lib/utils.js' {
  declare module.exports: $Exports<'i18next-http-backend/lib/utils'>;
}
