// flow-typed signature: markdown-it-stub
// flow-typed version: <<STUB>>/markdown-it_v^14.3.0/flow_v0.294.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it' {
  declare module.exports: any;
}
