allowBuilds:
  '@parcel/watcher': true
  puppeteer: true
  spawn-sync: true
  unrs-resolver: true
  core-js: true

minimumReleaseAgeExclude:
  - '@tardo/trash@2.2.0'
  - '@tardo/trash-stdlib@2.0.0'

overrides:
  jest-environment-puppeteer>jest-environment-node: '^30'
