allowBuilds:
  '@parcel/watcher': true
  puppeteer: true
  spawn-sync: true
  unrs-resolver: true
  core-js: true

minimumReleaseAgeExclude:
  - '@tardo/trash@1.0.0'

overrides:
  jest-environment-puppeteer>jest-environment-node: '^30'

patchedDependencies:
  '@tardo/trash@1.0.0': patches/@tardo__trash@1.0.0.patch
