// @flow strict
// Copyright  Alexandre Díaz <dev@redneboa.es>
// License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

type SettingType = 'edit' | 'json' | 'check' | 'manual' | 'option' | 'int' | 'color';

export const SETTING_TYPES: {
  init_cmds: SettingType,
  term_context: SettingType,
  pinned: SettingType,
  maximized: SettingType,
  multiline: SettingType,
  opacity: SettingType,
  elephant: SettingType,
  shortcuts: SettingType,
  devmode_tests: SettingType,
  devmode_ignore_comp_checks: SettingType,
  devmode_console_errors: SettingType,
  cmd_assistant_dyn_options_disabled: SettingType,
  cmd_assistant_match_mode: SettingType,
  cmd_assistant_max_results: SettingType,
  language: SettingType,
  fontsize: SettingType,
  fontsize_ca: SettingType,
  fontfamily: SettingType,
  color_primary: SettingType,
  color_secondary: SettingType,
  color_success: SettingType,
  color_danger: SettingType,
  color_warning: SettingType,
  color_info: SettingType,
  color_light: SettingType,
  color_dark: SettingType,
  color_muted: SettingType,
  color_white: SettingType,
  colors_domain: SettingType,
} = {
  init_cmds: 'edit',
  term_context: 'json',
  pinned: 'check',
  maximized: 'check',
  multiline: 'check',
  opacity: 'int',
  elephant: 'check',
  shortcuts: 'manual',
  devmode_tests: 'check',
  devmode_ignore_comp_checks: 'check',
  devmode_console_errors: 'check',
  cmd_assistant_dyn_options_disabled: 'check',
  cmd_assistant_match_mode: 'option',
  cmd_assistant_max_results: 'int',
  language: 'option',
  fontsize: 'option',
  fontsize_ca: 'option',
  fontfamily: 'edit',
  color_primary: 'color',
  color_secondary: 'color',
  color_success: 'color',
  color_danger: 'color',
  color_warning: 'color',
  color_info: 'color',
  color_light: 'color',
  color_dark: 'color',
  color_muted: 'color',
  color_white: 'color',
  colors_domain: 'manual',
};

export const SETTING_NAMES: $ReadOnlyArray<string> = Array.from(Object.keys(SETTING_TYPES));

export type ExtensionSettings = {
  init_cmds: string,
  term_context: {[string]: mixed},
  pinned: boolean,
  maximized: boolean,
  multiline: boolean,
  opacity: number,
  elephant: boolean,
  shortcuts: {[string]: string},
  devmode_tests: boolean,
  devmode_ignore_comp_checks: boolean,
  devmode_console_errors: boolean,
  cmd_assistant_dyn_options_disabled: boolean,
  cmd_assistant_match_mode: 'includes' | 'startsWith',
  cmd_assistant_max_results: number,
  language: 'auto' | 'en' | 'es',
  fontsize: 'small' | 'medium' | 'large',
  fontsize_ca: 'x-small' | 'small' | 'medium' | 'large',
  fontfamily: string,
  color_primary: string,
  color_secondary: string,
  color_success: string,
  color_danger: string,
  color_warning: string,
  color_info: string,
  color_light: string,
  color_dark: string,
  color_muted: string,
  color_white: string,
  colors_domain: {[string]: string},
};

export const SETTING_DEFAULTS: ExtensionSettings = {
  init_cmds: '',
  term_context: {active_test: false},
  pinned: false,
  maximized: false,
  multiline: false,
  opacity: 93,
  elephant: false,
  shortcuts: {},
  devmode_tests: false,
  devmode_ignore_comp_checks: false,
  devmode_console_errors: false,
  cmd_assistant_dyn_options_disabled: false,
  cmd_assistant_match_mode: 'includes',
  cmd_assistant_max_results: 35,
  language: 'auto',
  fontsize: 'medium',
  fontsize_ca: 'small',
  fontfamily: "'Lucida Console', Monaco, monospace",
  color_primary: '#3093fd',
  color_secondary: '#677886',
  color_success: '#28a745',
  color_danger: '#dc3545',
  color_warning: '#ffc107',
  color_info: '#97e9f6',
  color_light: '#f8f9fa',
  color_dark: '#343a40',
  color_muted: '#6c757d',
  color_white: '#ffffff',
  colors_domain: {},
};

export const IGNORED_KEYS: $ReadOnlyArray<string> = ['Control', 'Meta', 'Shift', 'Alt', 'Escape'];

export const VERSION_COLOR = {
  normal: '#71639e',
  disabled: '#878787',
  saas: '#9e7163',
  enterprise: '#c0c18a',
}

export const COMPATIBLE_VERSIONS: $ReadOnlyArray<string> = [
  '11.',
  'saas~11',
  '12.',
  'saas~12',
  '13.',
  'saas~13',
  '14.',
  'saas~14',
  '15.',
  'saas~15',
  '16.',
  'saas~16',
  '17.',
  'saas~17',
  '18.',
  'saas~18',
];

export const THEMES: $ReadOnlyArray<[string, string]> = [
  ['dark', 'Dark'],
  ['light', 'Light'],
  ['odoo', 'Odoo'],
  ['matrix', 'Matrix'],
]
