// @flow strict
// Copyright  Alexandre Díaz <dev@redneboa.es>
// License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import cmdBarcode from './barcode';
import cmdCaf from './caf';
import cmdCall from './call';
import cmdCam from './cam';
import cmdCommit from './commit';
import cmdContext from './context';
import cmdCopy from './copy';
import cmdCount from './count';
import cmdCreate from './create';
import cmdDBList from './dblist';
import cmdDebug from './debug';
import cmdDepends from './depends';
import cmdGen from './gen';
import cmdInstall from './install';
import cmdJson from './json';
import cmdJSTest from './jstest';
import cmdLastSeen from './lastseen';
import cmdLogin from './login';
import cmdLogout from './logout';
import cmdLongpolling from './longpolling';
import cmdMetadata from './metadata';
import cmdPaste from './paste';
import cmdNow from './now';
import cmdPost from './post';
import cmdRead from './read';
import cmdRef from './ref';
import cmdReload from './reload';
import cmdRollback from './rollback';
import cmdRpc from './rpc';
import cmdSearch from './search';
import cmdSysParam from './sysparam';
import cmdTour from './tour';
import cmdUal from './ual';
import cmdUhg from './uhg';
import cmdUninstall from './uninstall';
import cmdUnlink from './unlink';
import cmdUpgrade from './upgrade';
import cmdVersion from './version';
import cmdWhoami from './whoami';
import cmdWrite from './write';
import cmdWS from './ws';
import cmdURL from './url';
import cmdInfo from './info';
import cmdNotify from './notify';
import cmdExportFile from './exportfile';
import cmdRenewDatabase from './renew_database';
import type VMachine from '@trash/vmachine';

export default function (vm: VMachine) {
  vm.registerCommand('gen', cmdGen());
  vm.registerCommand('create', cmdCreate());
  vm.registerCommand('unlink', cmdUnlink());
  vm.registerCommand('write', cmdWrite());
  vm.registerCommand('search', cmdSearch());
  vm.registerCommand('call', cmdCall());
  vm.registerCommand('upgrade', cmdUpgrade());
  vm.registerCommand('install', cmdInstall());
  vm.registerCommand('uninstall', cmdUninstall());
  vm.registerCommand('reload', cmdReload());
  vm.registerCommand('debug', cmdDebug());
  vm.registerCommand('post', cmdPost());
  vm.registerCommand('whoami', cmdWhoami());
  vm.registerCommand('caf', cmdCaf());
  vm.registerCommand('cam', cmdCam());
  vm.registerCommand('lastseen', cmdLastSeen());
  vm.registerCommand('read', cmdRead());
  vm.registerCommand('context', cmdContext());
  vm.registerCommand('copy', cmdCopy());
  vm.registerCommand('version', cmdVersion());
  vm.registerCommand('longpolling', cmdLongpolling());
  vm.registerCommand('login', cmdLogin());
  vm.registerCommand('uhg', cmdUhg());
  vm.registerCommand('dblist', cmdDBList());
  vm.registerCommand('jstest', cmdJSTest());
  vm.registerCommand('tour', cmdTour());
  vm.registerCommand('json', cmdJson());
  vm.registerCommand('depends', cmdDepends());
  vm.registerCommand('ual', cmdUal());
  vm.registerCommand('logout', cmdLogout());
  vm.registerCommand('count', cmdCount());
  vm.registerCommand('ref', cmdRef());
  vm.registerCommand('rpc', cmdRpc());
  vm.registerCommand('metadata', cmdMetadata());
  vm.registerCommand('paste', cmdPaste());
  vm.registerCommand('barcode', cmdBarcode());
  vm.registerCommand('ws', cmdWS());
  vm.registerCommand('commit', cmdCommit());
  vm.registerCommand('rollback', cmdRollback());
  vm.registerCommand('now', cmdNow());
  vm.registerCommand('url', cmdURL());
  vm.registerCommand('info', cmdInfo());
  vm.registerCommand('notify', cmdNotify());
  vm.registerCommand('exportfile', cmdExportFile());
  vm.registerCommand('sysparam', cmdSysParam());
  vm.registerCommand('renew_database', cmdRenewDatabase());
}
