// Copyright  Alexandre Díaz <dev@redneboa.es>
// License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import cmdGen from "./gen";
import cmdCreate from "./create";
import cmdUnlink from "./unlink";
import cmdWrite from "./write";
import cmdSearch from "./search";
import cmdCall from "./call";
import cmdUpgrade from "./upgrade";
import cmdInstall from "./install";
import cmdUninstall from "./uninstall";
import cmdReload from "./reload";
import cmdDebug from "./debug";
import cmdPost from "./post";
import cmdWhoami from "./whoami";
import cmdCaf from "./caf";
import cmdCam from "./cam";
import cmdLastSeen from "./lastseen";
import cmdRead from "./read";
import cmdContext from "./context";
import cmdVersion from "./version";
import cmdLongpolling from "./longpolling";
import cmdLogin from "./login";
import cmdUhg from "./uhg";
import cmdDBList from "./dblist";
import cmdJSTest from "./jstest";
import cmdTour from "./tour";
import cmdJson from "./json";
import cmdDepends from "./depends";
import cmdUal from "./ual";
import cmdLogout from "./logout";
import cmdCount from "./count";
import cmdRef from "./ref";
import cmdRpc from "./rpc";
import cmdMetadata from "./metadata";
import cmdBarcode from "./barcode";
import cmdWS from "./ws";
import cmdCommit from "./commit";
import cmdRollback from "./rollback";
import cmdNow from "./now";

export default function (TerminalObj) {
  TerminalObj.registerCommand("gen", cmdGen);
  TerminalObj.registerCommand("create", cmdCreate);
  TerminalObj.registerCommand("unlink", cmdUnlink);
  TerminalObj.registerCommand("write", cmdWrite);
  TerminalObj.registerCommand("search", cmdSearch);
  TerminalObj.registerCommand("call", cmdCall);
  TerminalObj.registerCommand("upgrade", cmdUpgrade);
  TerminalObj.registerCommand("install", cmdInstall);
  TerminalObj.registerCommand("uninstall", cmdUninstall);
  TerminalObj.registerCommand("reload", cmdReload);
  TerminalObj.registerCommand("debug", cmdDebug);
  TerminalObj.registerCommand("post", cmdPost);
  TerminalObj.registerCommand("whoami", cmdWhoami);
  TerminalObj.registerCommand("caf", cmdCaf);
  TerminalObj.registerCommand("cam", cmdCam);
  TerminalObj.registerCommand("lastseen", cmdLastSeen);
  TerminalObj.registerCommand("read", cmdRead);
  TerminalObj.registerCommand("context", cmdContext);
  TerminalObj.registerCommand("version", cmdVersion);
  TerminalObj.registerCommand("longpolling", cmdLongpolling);
  TerminalObj.registerCommand("login", cmdLogin);
  TerminalObj.registerCommand("uhg", cmdUhg);
  TerminalObj.registerCommand("dblist", cmdDBList);
  TerminalObj.registerCommand("jstest", cmdJSTest);
  TerminalObj.registerCommand("tour", cmdTour);
  TerminalObj.registerCommand("json", cmdJson);
  TerminalObj.registerCommand("depends", cmdDepends);
  TerminalObj.registerCommand("ual", cmdUal);
  TerminalObj.registerCommand("logout", cmdLogout);
  TerminalObj.registerCommand("count", cmdCount);
  TerminalObj.registerCommand("ref", cmdRef);
  TerminalObj.registerCommand("rpc", cmdRpc);
  TerminalObj.registerCommand("metadata", cmdMetadata);
  TerminalObj.registerCommand("barcode", cmdBarcode);
  TerminalObj.registerCommand("ws", cmdWS);
  TerminalObj.registerCommand("commit", cmdCommit);
  TerminalObj.registerCommand("rollback", cmdRollback);
  TerminalObj.registerCommand("now", cmdNow);
}
