name: Tests

on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validations:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git checkout ${{ env.BRANCH }}

      - uses: actions/setup-node@v4
        with:
          node-version: '*'
          check-latest: true

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: flowjs
        run: pnpm run dev:flowcheck

      - name: eslint
        run: pnpm run dev:eslint

      - name: Build dist/ files
        run: pnpm run prod:build

      - name: web-ext
        run: pnpm run dev:web-ext

  jest-puppeteer:
    name: Jest-Puppeteer Tests
    needs: validations
    strategy:
      matrix:
        # Use only lower and active versions
        instance: ['11.0', '17.0', '18.0', '19.0']
        browser: [chrome]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to current branch
        run: git checkout ${{ env.BRANCH }}

      - uses: actions/setup-node@v4
        with:
          node-version: '*'
          check-latest: true

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install browser firefox
        run: npx @puppeteer/browsers install firefox
        if: ${{ matrix.browser == 'firefox' }}

      - name: Install browser chrome
        run: npx @puppeteer/browsers install chrome
        if: ${{ matrix.browser == 'chrome' }}

      - name: Run test for ${{ matrix.instance }} (${{ matrix.browser }})
        id: jest
        run: pnpm run test
        env:
          ODOO_VERSION: "${{ matrix.instance }}"
          PUPPETEER_BROWSER: "${{ matrix.browser }}"
